// Public
#pragma once
#include <stdint.h>
#include <unordered_map>

namespace amun
{
	enum EVoiceChatErrors
	{
		VOICE_CHAT_ERROR_NONE = 0,

		VOICE_CHAT_ERROR_FAILED_TO_INIT_CAPTURE_DEVICE,
		VOICE_CHAT_ERROR_FAILED_TO_START_CAPTURE_DEVICE,

		VOICE_CHAT_ERROR_FAILED_TO_INIT_PLAYBACK_DEVICE,
		VOICE_CHAT_ERROR_FAILED_TO_START_PLAYBACK_DEVICE,

		VOICE_CHAT_ERROR_FAILED_TO_INIT_ENCODER,
		VOICE_CHAT_ERROR_FAILED_TO_INIT_DECODER,

		VOICE_CHAT_ERROR_FAILED_TO_ENCODE,
		VOICE_CHAT_ERROR_FAILED_TO_DECODE,
	};
}
